version: '3.8'
services:
  redis:
    container_name: redis2
    image: redis:7.2.4-alpine
    restart: always
    ports:
        - 6379:6379
    # volumes:
    #   - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  container1:
    container_name: container_x1
    build: ./cluster
    ports:
      - 8001:8000
    working_dir: /app
    volumes:
      - ./cluster:/app/
    command: nodemon --exec go run main.go --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - CONTAINER_ID=1
      - ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/cluster-x/ecs-container-metadata.json
  container2:
    container_name: container_x2
    build: ./cluster
    ports:
      - 8002:8000
    working_dir: /app
    volumes:
      - ./cluster:/app/
    command: nodemon --exec go run main.go --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - CONTAINER_ID=2
      - ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/cluster-x/ecs-container-metadata.json
  container3:
    container_name: container_x3
    build: ./cluster
    ports:
      - 8003:8000
    working_dir: /app
    volumes:
      - ./cluster:/app/
    command: nodemon --exec go run main.go --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - CONTAINER_ID=3
      - ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/cluster-x/ecs-container-metadata.json
  container4:
    container_name: container_y1
    build: ./cluster
    ports:
      - 8004:8000
    working_dir: /app
    volumes:
      - ./cluster:/app/
    command: nodemon --exec go run main.go --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - CONTAINER_ID=4
      - ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/cluster-y/ecs-container-metadata.json
  container5:
    container_name: container_y2
    build: ./cluster
    ports:
      - 8005:8000
    working_dir: /app
    volumes:
      - ./cluster:/app/
    command: nodemon --exec go run main.go --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - CONTAINER_ID=5
      - ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/cluster-y/ecs-container-metadata.json
  container6:
    container_name: container_y3
    build: ./cluster
    ports:
      - 8006:8000
    working_dir: /app
    volumes:
      - ./cluster:/app/
    command: nodemon --exec go run main.go --signal SIGTERM --legacy-watch --ext .go,.mod,.sum
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - CONTAINER_ID=6
      - ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/cluster-y/ecs-container-metadata.json
